site_name: CITORUS.DOCS
site_url: http://docs.citorus.ru
site_description: Описание конфигурации «Кедр.Диспетчерский пункт»
site_author: CITORUS TEAM
site_favicon: favicon.ico
copyright: (c) ООО "Инфогрэйс", 2017
pages:
- 1. Описание конфигурации "КЕДР.Диспетчерский пункт: 'index.md'
